<div class="sub_navigation">
	<ol>
		<li class="selected">iCompute Tours Mobile Application</li>
	</ol>
	<div class="clear_both"></div>
</div>
<div class='pagecontent'>
	<span><strong>Welcome to the iCompute Tours Mobile Application website!</strong></span>
    <p>Here you can find information about how to use the application, enrich your own applications with our <a href="<?=$this->url(array(
                        'module'        => 'api',
                        'controller'	=> 'index',
                        'action'		=> 'index'), null, true);?>">RESTful API</a>, or send us feedback regarding the application itself.</p>
</div>
<div class='pagecontentbottom'></div>